version: '3.8'

services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: gunicorn django_docker_example_app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/django-user/web/staticfiles
      - media_volume:/home/django-user/web/mediafiles
    env_file:
      - ./.env
    expose:
      - 8000
  nginx-proxy:
    container_name: nginx-proxy
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - '443:443'
      - '80:80'
    volumes:
      - static_volume:/home/django-user/web/staticfiles
      - media_volume:/home/django-user/web/mediafiles
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - web
  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    env_file:
      - ./.env.staging.proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - acme:/etc/acme.sh
    depends_on:
      - nginx-proxy

volumes:
  static_volume:
  media_volume:
  certs:
  html:
  vhost:
  acme:

