version: '3.8'

services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: gunicorn django_docker_example_app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/django-user/web/staticfiles
      - media_volume:/home/django-user/web/mediafiles
    env_file:
      - ./.env
    expose:
      - 8000
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    volumes:
      - static_volume:/home/django-user/web/staticfiles
      - media_volume:/home/django-user/web/mediafiles
    ports:
      - '1337:80'
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:


