version: '3.10'

services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: gunicorn django_docker_example_app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/django-user/web/staticfiles
    env_file:
      - ./.env
    depends_on:
      - db
    expose:
      - 8000
  db:
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/django-user/web/staticfiles
    ports:
      - '1337:80'
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:


